// Code generated by goctl. DO NOT EDIT.
// Source: mcms.proto

package mcmsclient

import (
	"context"

	"github.com/suyuan32/simple-admin-message-center/types/mcms"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BaseIDResp   = mcms.BaseIDResp
	BaseResp     = mcms.BaseResp
	BaseUUIDResp = mcms.BaseUUIDResp
	Empty        = mcms.Empty
	IDReq        = mcms.IDReq
	IDsReq       = mcms.IDsReq
	PageInfoReq  = mcms.PageInfoReq
	UUIDReq      = mcms.UUIDReq
	UUIDsReq     = mcms.UUIDsReq

	Mcms interface {
		InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error)
	}

	defaultMcms struct {
		cli zrpc.Client
	}
)

func NewMcms(cli zrpc.Client) Mcms {
	return &defaultMcms{
		cli: cli,
	}
}

func (m *defaultMcms) InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error) {
	client := mcms.NewMcmsClient(m.cli.Conn())
	return client.InitDatabase(ctx, in, opts...)
}
