// Code generated by goctl. DO NOT EDIT.
// Source: mcms.proto

package server

import (
	"context"

	"github.com/suyuan32/simple-admin-message-center/internal/logic/base"
	"github.com/suyuan32/simple-admin-message-center/internal/svc"
	"github.com/suyuan32/simple-admin-message-center/types/mcms"
)

type McmsServer struct {
	svcCtx *svc.ServiceContext
	mcms.UnimplementedMcmsServer
}

func NewMcmsServer(svcCtx *svc.ServiceContext) *McmsServer {
	return &McmsServer{
		svcCtx: svcCtx,
	}
}

func (s *McmsServer) InitDatabase(ctx context.Context, in *mcms.Empty) (*mcms.BaseResp, error) {
	l := base.NewInitDatabaseLogic(ctx, s.svcCtx)
	return l.InitDatabase(in)
}
