// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.2
// source: mcms.proto

package mcms

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Mcms_InitDatabase_FullMethodName         = "/mcms.Mcms/initDatabase"
	Mcms_SendEmail_FullMethodName            = "/mcms.Mcms/sendEmail"
	Mcms_CreateEmailLog_FullMethodName       = "/mcms.Mcms/createEmailLog"
	Mcms_UpdateEmailLog_FullMethodName       = "/mcms.Mcms/updateEmailLog"
	Mcms_GetEmailLogList_FullMethodName      = "/mcms.Mcms/getEmailLogList"
	Mcms_GetEmailLogById_FullMethodName      = "/mcms.Mcms/getEmailLogById"
	Mcms_DeleteEmailLog_FullMethodName       = "/mcms.Mcms/deleteEmailLog"
	Mcms_CreateEmailProvider_FullMethodName  = "/mcms.Mcms/createEmailProvider"
	Mcms_UpdateEmailProvider_FullMethodName  = "/mcms.Mcms/updateEmailProvider"
	Mcms_GetEmailProviderList_FullMethodName = "/mcms.Mcms/getEmailProviderList"
	Mcms_GetEmailProviderById_FullMethodName = "/mcms.Mcms/getEmailProviderById"
	Mcms_DeleteEmailProvider_FullMethodName  = "/mcms.Mcms/deleteEmailProvider"
	Mcms_SendSms_FullMethodName              = "/mcms.Mcms/sendSms"
	Mcms_CreateSmsLog_FullMethodName         = "/mcms.Mcms/createSmsLog"
	Mcms_UpdateSmsLog_FullMethodName         = "/mcms.Mcms/updateSmsLog"
	Mcms_GetSmsLogList_FullMethodName        = "/mcms.Mcms/getSmsLogList"
	Mcms_GetSmsLogById_FullMethodName        = "/mcms.Mcms/getSmsLogById"
	Mcms_DeleteSmsLog_FullMethodName         = "/mcms.Mcms/deleteSmsLog"
	Mcms_CreateSmsProvider_FullMethodName    = "/mcms.Mcms/createSmsProvider"
	Mcms_UpdateSmsProvider_FullMethodName    = "/mcms.Mcms/updateSmsProvider"
	Mcms_GetSmsProviderList_FullMethodName   = "/mcms.Mcms/getSmsProviderList"
	Mcms_GetSmsProviderById_FullMethodName   = "/mcms.Mcms/getSmsProviderById"
	Mcms_DeleteSmsProvider_FullMethodName    = "/mcms.Mcms/deleteSmsProvider"
)

// McmsClient is the client API for Mcms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type McmsClient interface {
	// group: base
	InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error)
	//  group: email
	SendEmail(ctx context.Context, in *EmailInfo, opts ...grpc.CallOption) (*BaseUUIDResp, error)
	//  EmailLog management
	//  group: emaillog
	CreateEmailLog(ctx context.Context, in *EmailLogInfo, opts ...grpc.CallOption) (*BaseUUIDResp, error)
	//  group: emaillog
	UpdateEmailLog(ctx context.Context, in *EmailLogInfo, opts ...grpc.CallOption) (*BaseResp, error)
	//  group: emaillog
	GetEmailLogList(ctx context.Context, in *EmailLogListReq, opts ...grpc.CallOption) (*EmailLogListResp, error)
	//  group: emaillog
	GetEmailLogById(ctx context.Context, in *UUIDReq, opts ...grpc.CallOption) (*EmailLogInfo, error)
	//  group: emaillog
	DeleteEmailLog(ctx context.Context, in *UUIDsReq, opts ...grpc.CallOption) (*BaseResp, error)
	//  EmailProvider management
	//  group: emailprovider
	CreateEmailProvider(ctx context.Context, in *EmailProviderInfo, opts ...grpc.CallOption) (*BaseIDResp, error)
	//  group: emailprovider
	UpdateEmailProvider(ctx context.Context, in *EmailProviderInfo, opts ...grpc.CallOption) (*BaseResp, error)
	//  group: emailprovider
	GetEmailProviderList(ctx context.Context, in *EmailProviderListReq, opts ...grpc.CallOption) (*EmailProviderListResp, error)
	//  group: emailprovider
	GetEmailProviderById(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*EmailProviderInfo, error)
	//  group: emailprovider
	DeleteEmailProvider(ctx context.Context, in *IDsReq, opts ...grpc.CallOption) (*BaseResp, error)
	//  group: sms
	SendSms(ctx context.Context, in *SmsInfo, opts ...grpc.CallOption) (*BaseUUIDResp, error)
	//  SmsLog management
	//  group: smslog
	CreateSmsLog(ctx context.Context, in *SmsLogInfo, opts ...grpc.CallOption) (*BaseUUIDResp, error)
	//  group: smslog
	UpdateSmsLog(ctx context.Context, in *SmsLogInfo, opts ...grpc.CallOption) (*BaseResp, error)
	//  group: smslog
	GetSmsLogList(ctx context.Context, in *SmsLogListReq, opts ...grpc.CallOption) (*SmsLogListResp, error)
	//  group: smslog
	GetSmsLogById(ctx context.Context, in *UUIDReq, opts ...grpc.CallOption) (*SmsLogInfo, error)
	//  group: smslog
	DeleteSmsLog(ctx context.Context, in *UUIDsReq, opts ...grpc.CallOption) (*BaseResp, error)
	//  SmsProvider management
	//  group: smsprovider
	CreateSmsProvider(ctx context.Context, in *SmsProviderInfo, opts ...grpc.CallOption) (*BaseIDResp, error)
	//  group: smsprovider
	UpdateSmsProvider(ctx context.Context, in *SmsProviderInfo, opts ...grpc.CallOption) (*BaseResp, error)
	//  group: smsprovider
	GetSmsProviderList(ctx context.Context, in *SmsProviderListReq, opts ...grpc.CallOption) (*SmsProviderListResp, error)
	//  group: smsprovider
	GetSmsProviderById(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*SmsProviderInfo, error)
	//  group: smsprovider
	DeleteSmsProvider(ctx context.Context, in *IDsReq, opts ...grpc.CallOption) (*BaseResp, error)
}

type mcmsClient struct {
	cc grpc.ClientConnInterface
}

func NewMcmsClient(cc grpc.ClientConnInterface) McmsClient {
	return &mcmsClient{cc}
}

func (c *mcmsClient) InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error) {
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Mcms_InitDatabase_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcmsClient) SendEmail(ctx context.Context, in *EmailInfo, opts ...grpc.CallOption) (*BaseUUIDResp, error) {
	out := new(BaseUUIDResp)
	err := c.cc.Invoke(ctx, Mcms_SendEmail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcmsClient) CreateEmailLog(ctx context.Context, in *EmailLogInfo, opts ...grpc.CallOption) (*BaseUUIDResp, error) {
	out := new(BaseUUIDResp)
	err := c.cc.Invoke(ctx, Mcms_CreateEmailLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcmsClient) UpdateEmailLog(ctx context.Context, in *EmailLogInfo, opts ...grpc.CallOption) (*BaseResp, error) {
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Mcms_UpdateEmailLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcmsClient) GetEmailLogList(ctx context.Context, in *EmailLogListReq, opts ...grpc.CallOption) (*EmailLogListResp, error) {
	out := new(EmailLogListResp)
	err := c.cc.Invoke(ctx, Mcms_GetEmailLogList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcmsClient) GetEmailLogById(ctx context.Context, in *UUIDReq, opts ...grpc.CallOption) (*EmailLogInfo, error) {
	out := new(EmailLogInfo)
	err := c.cc.Invoke(ctx, Mcms_GetEmailLogById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcmsClient) DeleteEmailLog(ctx context.Context, in *UUIDsReq, opts ...grpc.CallOption) (*BaseResp, error) {
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Mcms_DeleteEmailLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcmsClient) CreateEmailProvider(ctx context.Context, in *EmailProviderInfo, opts ...grpc.CallOption) (*BaseIDResp, error) {
	out := new(BaseIDResp)
	err := c.cc.Invoke(ctx, Mcms_CreateEmailProvider_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcmsClient) UpdateEmailProvider(ctx context.Context, in *EmailProviderInfo, opts ...grpc.CallOption) (*BaseResp, error) {
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Mcms_UpdateEmailProvider_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcmsClient) GetEmailProviderList(ctx context.Context, in *EmailProviderListReq, opts ...grpc.CallOption) (*EmailProviderListResp, error) {
	out := new(EmailProviderListResp)
	err := c.cc.Invoke(ctx, Mcms_GetEmailProviderList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcmsClient) GetEmailProviderById(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*EmailProviderInfo, error) {
	out := new(EmailProviderInfo)
	err := c.cc.Invoke(ctx, Mcms_GetEmailProviderById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcmsClient) DeleteEmailProvider(ctx context.Context, in *IDsReq, opts ...grpc.CallOption) (*BaseResp, error) {
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Mcms_DeleteEmailProvider_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcmsClient) SendSms(ctx context.Context, in *SmsInfo, opts ...grpc.CallOption) (*BaseUUIDResp, error) {
	out := new(BaseUUIDResp)
	err := c.cc.Invoke(ctx, Mcms_SendSms_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcmsClient) CreateSmsLog(ctx context.Context, in *SmsLogInfo, opts ...grpc.CallOption) (*BaseUUIDResp, error) {
	out := new(BaseUUIDResp)
	err := c.cc.Invoke(ctx, Mcms_CreateSmsLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcmsClient) UpdateSmsLog(ctx context.Context, in *SmsLogInfo, opts ...grpc.CallOption) (*BaseResp, error) {
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Mcms_UpdateSmsLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcmsClient) GetSmsLogList(ctx context.Context, in *SmsLogListReq, opts ...grpc.CallOption) (*SmsLogListResp, error) {
	out := new(SmsLogListResp)
	err := c.cc.Invoke(ctx, Mcms_GetSmsLogList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcmsClient) GetSmsLogById(ctx context.Context, in *UUIDReq, opts ...grpc.CallOption) (*SmsLogInfo, error) {
	out := new(SmsLogInfo)
	err := c.cc.Invoke(ctx, Mcms_GetSmsLogById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcmsClient) DeleteSmsLog(ctx context.Context, in *UUIDsReq, opts ...grpc.CallOption) (*BaseResp, error) {
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Mcms_DeleteSmsLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcmsClient) CreateSmsProvider(ctx context.Context, in *SmsProviderInfo, opts ...grpc.CallOption) (*BaseIDResp, error) {
	out := new(BaseIDResp)
	err := c.cc.Invoke(ctx, Mcms_CreateSmsProvider_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcmsClient) UpdateSmsProvider(ctx context.Context, in *SmsProviderInfo, opts ...grpc.CallOption) (*BaseResp, error) {
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Mcms_UpdateSmsProvider_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcmsClient) GetSmsProviderList(ctx context.Context, in *SmsProviderListReq, opts ...grpc.CallOption) (*SmsProviderListResp, error) {
	out := new(SmsProviderListResp)
	err := c.cc.Invoke(ctx, Mcms_GetSmsProviderList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcmsClient) GetSmsProviderById(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*SmsProviderInfo, error) {
	out := new(SmsProviderInfo)
	err := c.cc.Invoke(ctx, Mcms_GetSmsProviderById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcmsClient) DeleteSmsProvider(ctx context.Context, in *IDsReq, opts ...grpc.CallOption) (*BaseResp, error) {
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Mcms_DeleteSmsProvider_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// McmsServer is the server API for Mcms service.
// All implementations must embed UnimplementedMcmsServer
// for forward compatibility
type McmsServer interface {
	// group: base
	InitDatabase(context.Context, *Empty) (*BaseResp, error)
	//  group: email
	SendEmail(context.Context, *EmailInfo) (*BaseUUIDResp, error)
	//  EmailLog management
	//  group: emaillog
	CreateEmailLog(context.Context, *EmailLogInfo) (*BaseUUIDResp, error)
	//  group: emaillog
	UpdateEmailLog(context.Context, *EmailLogInfo) (*BaseResp, error)
	//  group: emaillog
	GetEmailLogList(context.Context, *EmailLogListReq) (*EmailLogListResp, error)
	//  group: emaillog
	GetEmailLogById(context.Context, *UUIDReq) (*EmailLogInfo, error)
	//  group: emaillog
	DeleteEmailLog(context.Context, *UUIDsReq) (*BaseResp, error)
	//  EmailProvider management
	//  group: emailprovider
	CreateEmailProvider(context.Context, *EmailProviderInfo) (*BaseIDResp, error)
	//  group: emailprovider
	UpdateEmailProvider(context.Context, *EmailProviderInfo) (*BaseResp, error)
	//  group: emailprovider
	GetEmailProviderList(context.Context, *EmailProviderListReq) (*EmailProviderListResp, error)
	//  group: emailprovider
	GetEmailProviderById(context.Context, *IDReq) (*EmailProviderInfo, error)
	//  group: emailprovider
	DeleteEmailProvider(context.Context, *IDsReq) (*BaseResp, error)
	//  group: sms
	SendSms(context.Context, *SmsInfo) (*BaseUUIDResp, error)
	//  SmsLog management
	//  group: smslog
	CreateSmsLog(context.Context, *SmsLogInfo) (*BaseUUIDResp, error)
	//  group: smslog
	UpdateSmsLog(context.Context, *SmsLogInfo) (*BaseResp, error)
	//  group: smslog
	GetSmsLogList(context.Context, *SmsLogListReq) (*SmsLogListResp, error)
	//  group: smslog
	GetSmsLogById(context.Context, *UUIDReq) (*SmsLogInfo, error)
	//  group: smslog
	DeleteSmsLog(context.Context, *UUIDsReq) (*BaseResp, error)
	//  SmsProvider management
	//  group: smsprovider
	CreateSmsProvider(context.Context, *SmsProviderInfo) (*BaseIDResp, error)
	//  group: smsprovider
	UpdateSmsProvider(context.Context, *SmsProviderInfo) (*BaseResp, error)
	//  group: smsprovider
	GetSmsProviderList(context.Context, *SmsProviderListReq) (*SmsProviderListResp, error)
	//  group: smsprovider
	GetSmsProviderById(context.Context, *IDReq) (*SmsProviderInfo, error)
	//  group: smsprovider
	DeleteSmsProvider(context.Context, *IDsReq) (*BaseResp, error)
	mustEmbedUnimplementedMcmsServer()
}

// UnimplementedMcmsServer must be embedded to have forward compatible implementations.
type UnimplementedMcmsServer struct {
}

func (UnimplementedMcmsServer) InitDatabase(context.Context, *Empty) (*BaseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitDatabase not implemented")
}
func (UnimplementedMcmsServer) SendEmail(context.Context, *EmailInfo) (*BaseUUIDResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}
func (UnimplementedMcmsServer) CreateEmailLog(context.Context, *EmailLogInfo) (*BaseUUIDResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEmailLog not implemented")
}
func (UnimplementedMcmsServer) UpdateEmailLog(context.Context, *EmailLogInfo) (*BaseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEmailLog not implemented")
}
func (UnimplementedMcmsServer) GetEmailLogList(context.Context, *EmailLogListReq) (*EmailLogListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmailLogList not implemented")
}
func (UnimplementedMcmsServer) GetEmailLogById(context.Context, *UUIDReq) (*EmailLogInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmailLogById not implemented")
}
func (UnimplementedMcmsServer) DeleteEmailLog(context.Context, *UUIDsReq) (*BaseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEmailLog not implemented")
}
func (UnimplementedMcmsServer) CreateEmailProvider(context.Context, *EmailProviderInfo) (*BaseIDResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEmailProvider not implemented")
}
func (UnimplementedMcmsServer) UpdateEmailProvider(context.Context, *EmailProviderInfo) (*BaseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEmailProvider not implemented")
}
func (UnimplementedMcmsServer) GetEmailProviderList(context.Context, *EmailProviderListReq) (*EmailProviderListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmailProviderList not implemented")
}
func (UnimplementedMcmsServer) GetEmailProviderById(context.Context, *IDReq) (*EmailProviderInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmailProviderById not implemented")
}
func (UnimplementedMcmsServer) DeleteEmailProvider(context.Context, *IDsReq) (*BaseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEmailProvider not implemented")
}
func (UnimplementedMcmsServer) SendSms(context.Context, *SmsInfo) (*BaseUUIDResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSms not implemented")
}
func (UnimplementedMcmsServer) CreateSmsLog(context.Context, *SmsLogInfo) (*BaseUUIDResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSmsLog not implemented")
}
func (UnimplementedMcmsServer) UpdateSmsLog(context.Context, *SmsLogInfo) (*BaseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSmsLog not implemented")
}
func (UnimplementedMcmsServer) GetSmsLogList(context.Context, *SmsLogListReq) (*SmsLogListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSmsLogList not implemented")
}
func (UnimplementedMcmsServer) GetSmsLogById(context.Context, *UUIDReq) (*SmsLogInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSmsLogById not implemented")
}
func (UnimplementedMcmsServer) DeleteSmsLog(context.Context, *UUIDsReq) (*BaseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSmsLog not implemented")
}
func (UnimplementedMcmsServer) CreateSmsProvider(context.Context, *SmsProviderInfo) (*BaseIDResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSmsProvider not implemented")
}
func (UnimplementedMcmsServer) UpdateSmsProvider(context.Context, *SmsProviderInfo) (*BaseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSmsProvider not implemented")
}
func (UnimplementedMcmsServer) GetSmsProviderList(context.Context, *SmsProviderListReq) (*SmsProviderListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSmsProviderList not implemented")
}
func (UnimplementedMcmsServer) GetSmsProviderById(context.Context, *IDReq) (*SmsProviderInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSmsProviderById not implemented")
}
func (UnimplementedMcmsServer) DeleteSmsProvider(context.Context, *IDsReq) (*BaseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSmsProvider not implemented")
}
func (UnimplementedMcmsServer) mustEmbedUnimplementedMcmsServer() {}

// UnsafeMcmsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to McmsServer will
// result in compilation errors.
type UnsafeMcmsServer interface {
	mustEmbedUnimplementedMcmsServer()
}

func RegisterMcmsServer(s grpc.ServiceRegistrar, srv McmsServer) {
	s.RegisterService(&Mcms_ServiceDesc, srv)
}

func _Mcms_InitDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McmsServer).InitDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcms_InitDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McmsServer).InitDatabase(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcms_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McmsServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcms_SendEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McmsServer).SendEmail(ctx, req.(*EmailInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcms_CreateEmailLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailLogInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McmsServer).CreateEmailLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcms_CreateEmailLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McmsServer).CreateEmailLog(ctx, req.(*EmailLogInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcms_UpdateEmailLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailLogInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McmsServer).UpdateEmailLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcms_UpdateEmailLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McmsServer).UpdateEmailLog(ctx, req.(*EmailLogInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcms_GetEmailLogList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailLogListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McmsServer).GetEmailLogList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcms_GetEmailLogList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McmsServer).GetEmailLogList(ctx, req.(*EmailLogListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcms_GetEmailLogById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UUIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McmsServer).GetEmailLogById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcms_GetEmailLogById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McmsServer).GetEmailLogById(ctx, req.(*UUIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcms_DeleteEmailLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UUIDsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McmsServer).DeleteEmailLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcms_DeleteEmailLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McmsServer).DeleteEmailLog(ctx, req.(*UUIDsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcms_CreateEmailProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailProviderInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McmsServer).CreateEmailProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcms_CreateEmailProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McmsServer).CreateEmailProvider(ctx, req.(*EmailProviderInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcms_UpdateEmailProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailProviderInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McmsServer).UpdateEmailProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcms_UpdateEmailProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McmsServer).UpdateEmailProvider(ctx, req.(*EmailProviderInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcms_GetEmailProviderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailProviderListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McmsServer).GetEmailProviderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcms_GetEmailProviderList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McmsServer).GetEmailProviderList(ctx, req.(*EmailProviderListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcms_GetEmailProviderById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McmsServer).GetEmailProviderById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcms_GetEmailProviderById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McmsServer).GetEmailProviderById(ctx, req.(*IDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcms_DeleteEmailProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McmsServer).DeleteEmailProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcms_DeleteEmailProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McmsServer).DeleteEmailProvider(ctx, req.(*IDsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcms_SendSms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmsInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McmsServer).SendSms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcms_SendSms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McmsServer).SendSms(ctx, req.(*SmsInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcms_CreateSmsLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmsLogInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McmsServer).CreateSmsLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcms_CreateSmsLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McmsServer).CreateSmsLog(ctx, req.(*SmsLogInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcms_UpdateSmsLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmsLogInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McmsServer).UpdateSmsLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcms_UpdateSmsLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McmsServer).UpdateSmsLog(ctx, req.(*SmsLogInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcms_GetSmsLogList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmsLogListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McmsServer).GetSmsLogList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcms_GetSmsLogList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McmsServer).GetSmsLogList(ctx, req.(*SmsLogListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcms_GetSmsLogById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UUIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McmsServer).GetSmsLogById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcms_GetSmsLogById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McmsServer).GetSmsLogById(ctx, req.(*UUIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcms_DeleteSmsLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UUIDsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McmsServer).DeleteSmsLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcms_DeleteSmsLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McmsServer).DeleteSmsLog(ctx, req.(*UUIDsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcms_CreateSmsProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmsProviderInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McmsServer).CreateSmsProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcms_CreateSmsProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McmsServer).CreateSmsProvider(ctx, req.(*SmsProviderInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcms_UpdateSmsProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmsProviderInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McmsServer).UpdateSmsProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcms_UpdateSmsProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McmsServer).UpdateSmsProvider(ctx, req.(*SmsProviderInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcms_GetSmsProviderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmsProviderListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McmsServer).GetSmsProviderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcms_GetSmsProviderList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McmsServer).GetSmsProviderList(ctx, req.(*SmsProviderListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcms_GetSmsProviderById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McmsServer).GetSmsProviderById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcms_GetSmsProviderById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McmsServer).GetSmsProviderById(ctx, req.(*IDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcms_DeleteSmsProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McmsServer).DeleteSmsProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcms_DeleteSmsProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McmsServer).DeleteSmsProvider(ctx, req.(*IDsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Mcms_ServiceDesc is the grpc.ServiceDesc for Mcms service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mcms_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mcms.Mcms",
	HandlerType: (*McmsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "initDatabase",
			Handler:    _Mcms_InitDatabase_Handler,
		},
		{
			MethodName: "sendEmail",
			Handler:    _Mcms_SendEmail_Handler,
		},
		{
			MethodName: "createEmailLog",
			Handler:    _Mcms_CreateEmailLog_Handler,
		},
		{
			MethodName: "updateEmailLog",
			Handler:    _Mcms_UpdateEmailLog_Handler,
		},
		{
			MethodName: "getEmailLogList",
			Handler:    _Mcms_GetEmailLogList_Handler,
		},
		{
			MethodName: "getEmailLogById",
			Handler:    _Mcms_GetEmailLogById_Handler,
		},
		{
			MethodName: "deleteEmailLog",
			Handler:    _Mcms_DeleteEmailLog_Handler,
		},
		{
			MethodName: "createEmailProvider",
			Handler:    _Mcms_CreateEmailProvider_Handler,
		},
		{
			MethodName: "updateEmailProvider",
			Handler:    _Mcms_UpdateEmailProvider_Handler,
		},
		{
			MethodName: "getEmailProviderList",
			Handler:    _Mcms_GetEmailProviderList_Handler,
		},
		{
			MethodName: "getEmailProviderById",
			Handler:    _Mcms_GetEmailProviderById_Handler,
		},
		{
			MethodName: "deleteEmailProvider",
			Handler:    _Mcms_DeleteEmailProvider_Handler,
		},
		{
			MethodName: "sendSms",
			Handler:    _Mcms_SendSms_Handler,
		},
		{
			MethodName: "createSmsLog",
			Handler:    _Mcms_CreateSmsLog_Handler,
		},
		{
			MethodName: "updateSmsLog",
			Handler:    _Mcms_UpdateSmsLog_Handler,
		},
		{
			MethodName: "getSmsLogList",
			Handler:    _Mcms_GetSmsLogList_Handler,
		},
		{
			MethodName: "getSmsLogById",
			Handler:    _Mcms_GetSmsLogById_Handler,
		},
		{
			MethodName: "deleteSmsLog",
			Handler:    _Mcms_DeleteSmsLog_Handler,
		},
		{
			MethodName: "createSmsProvider",
			Handler:    _Mcms_CreateSmsProvider_Handler,
		},
		{
			MethodName: "updateSmsProvider",
			Handler:    _Mcms_UpdateSmsProvider_Handler,
		},
		{
			MethodName: "getSmsProviderList",
			Handler:    _Mcms_GetSmsProviderList_Handler,
		},
		{
			MethodName: "getSmsProviderById",
			Handler:    _Mcms_GetSmsProviderById_Handler,
		},
		{
			MethodName: "deleteSmsProvider",
			Handler:    _Mcms_DeleteSmsProvider_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mcms.proto",
}
