// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// McmsColumns holds the columns for the "mcms" table.
	McmsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// McmsTable holds the schema information for the "mcms" table.
	McmsTable = &schema.Table{
		Name:       "mcms",
		Columns:    McmsColumns,
		PrimaryKey: []*schema.Column{McmsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		McmsTable,
	}
)

func init() {
}
