// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/suyuan32/simple-admin-message-center/ent/emaillog"
)

// EmailLogCreate is the builder for creating a EmailLog entity.
type EmailLogCreate struct {
	config
	mutation *EmailLogMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (elc *EmailLogCreate) SetCreatedAt(t time.Time) *EmailLogCreate {
	elc.mutation.SetCreatedAt(t)
	return elc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (elc *EmailLogCreate) SetNillableCreatedAt(t *time.Time) *EmailLogCreate {
	if t != nil {
		elc.SetCreatedAt(*t)
	}
	return elc
}

// SetUpdatedAt sets the "updated_at" field.
func (elc *EmailLogCreate) SetUpdatedAt(t time.Time) *EmailLogCreate {
	elc.mutation.SetUpdatedAt(t)
	return elc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (elc *EmailLogCreate) SetNillableUpdatedAt(t *time.Time) *EmailLogCreate {
	if t != nil {
		elc.SetUpdatedAt(*t)
	}
	return elc
}

// SetTarget sets the "target" field.
func (elc *EmailLogCreate) SetTarget(s string) *EmailLogCreate {
	elc.mutation.SetTarget(s)
	return elc
}

// SetSubject sets the "subject" field.
func (elc *EmailLogCreate) SetSubject(s string) *EmailLogCreate {
	elc.mutation.SetSubject(s)
	return elc
}

// SetContent sets the "content" field.
func (elc *EmailLogCreate) SetContent(s string) *EmailLogCreate {
	elc.mutation.SetContent(s)
	return elc
}

// SetSendStatus sets the "send_status" field.
func (elc *EmailLogCreate) SetSendStatus(u uint8) *EmailLogCreate {
	elc.mutation.SetSendStatus(u)
	return elc
}

// SetID sets the "id" field.
func (elc *EmailLogCreate) SetID(u uuid.UUID) *EmailLogCreate {
	elc.mutation.SetID(u)
	return elc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (elc *EmailLogCreate) SetNillableID(u *uuid.UUID) *EmailLogCreate {
	if u != nil {
		elc.SetID(*u)
	}
	return elc
}

// Mutation returns the EmailLogMutation object of the builder.
func (elc *EmailLogCreate) Mutation() *EmailLogMutation {
	return elc.mutation
}

// Save creates the EmailLog in the database.
func (elc *EmailLogCreate) Save(ctx context.Context) (*EmailLog, error) {
	elc.defaults()
	return withHooks(ctx, elc.sqlSave, elc.mutation, elc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (elc *EmailLogCreate) SaveX(ctx context.Context) *EmailLog {
	v, err := elc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (elc *EmailLogCreate) Exec(ctx context.Context) error {
	_, err := elc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (elc *EmailLogCreate) ExecX(ctx context.Context) {
	if err := elc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (elc *EmailLogCreate) defaults() {
	if _, ok := elc.mutation.CreatedAt(); !ok {
		v := emaillog.DefaultCreatedAt()
		elc.mutation.SetCreatedAt(v)
	}
	if _, ok := elc.mutation.UpdatedAt(); !ok {
		v := emaillog.DefaultUpdatedAt()
		elc.mutation.SetUpdatedAt(v)
	}
	if _, ok := elc.mutation.ID(); !ok {
		v := emaillog.DefaultID()
		elc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (elc *EmailLogCreate) check() error {
	if _, ok := elc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EmailLog.created_at"`)}
	}
	if _, ok := elc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EmailLog.updated_at"`)}
	}
	if _, ok := elc.mutation.Target(); !ok {
		return &ValidationError{Name: "target", err: errors.New(`ent: missing required field "EmailLog.target"`)}
	}
	if _, ok := elc.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "EmailLog.subject"`)}
	}
	if _, ok := elc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "EmailLog.content"`)}
	}
	if _, ok := elc.mutation.SendStatus(); !ok {
		return &ValidationError{Name: "send_status", err: errors.New(`ent: missing required field "EmailLog.send_status"`)}
	}
	return nil
}

func (elc *EmailLogCreate) sqlSave(ctx context.Context) (*EmailLog, error) {
	if err := elc.check(); err != nil {
		return nil, err
	}
	_node, _spec := elc.createSpec()
	if err := sqlgraph.CreateNode(ctx, elc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	elc.mutation.id = &_node.ID
	elc.mutation.done = true
	return _node, nil
}

func (elc *EmailLogCreate) createSpec() (*EmailLog, *sqlgraph.CreateSpec) {
	var (
		_node = &EmailLog{config: elc.config}
		_spec = sqlgraph.NewCreateSpec(emaillog.Table, sqlgraph.NewFieldSpec(emaillog.FieldID, field.TypeUUID))
	)
	if id, ok := elc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := elc.mutation.CreatedAt(); ok {
		_spec.SetField(emaillog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := elc.mutation.UpdatedAt(); ok {
		_spec.SetField(emaillog.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := elc.mutation.Target(); ok {
		_spec.SetField(emaillog.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := elc.mutation.Subject(); ok {
		_spec.SetField(emaillog.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := elc.mutation.Content(); ok {
		_spec.SetField(emaillog.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := elc.mutation.SendStatus(); ok {
		_spec.SetField(emaillog.FieldSendStatus, field.TypeUint8, value)
		_node.SendStatus = value
	}
	return _node, _spec
}

// EmailLogCreateBulk is the builder for creating many EmailLog entities in bulk.
type EmailLogCreateBulk struct {
	config
	builders []*EmailLogCreate
}

// Save creates the EmailLog entities in the database.
func (elcb *EmailLogCreateBulk) Save(ctx context.Context) ([]*EmailLog, error) {
	specs := make([]*sqlgraph.CreateSpec, len(elcb.builders))
	nodes := make([]*EmailLog, len(elcb.builders))
	mutators := make([]Mutator, len(elcb.builders))
	for i := range elcb.builders {
		func(i int, root context.Context) {
			builder := elcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmailLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, elcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, elcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, elcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (elcb *EmailLogCreateBulk) SaveX(ctx context.Context) []*EmailLog {
	v, err := elcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (elcb *EmailLogCreateBulk) Exec(ctx context.Context) error {
	_, err := elcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (elcb *EmailLogCreateBulk) ExecX(ctx context.Context) {
	if err := elcb.Exec(ctx); err != nil {
		panic(err)
	}
}
