// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/suyuan32/simple-admin-message-center/ent/emaillog"
)

// EmailLogCreate is the builder for creating a EmailLog entity.
type EmailLogCreate struct {
	config
	mutation *EmailLogMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *EmailLogCreate) SetCreatedAt(v time.Time) *EmailLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EmailLogCreate) SetNillableCreatedAt(v *time.Time) *EmailLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EmailLogCreate) SetUpdatedAt(v time.Time) *EmailLogCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EmailLogCreate) SetNillableUpdatedAt(v *time.Time) *EmailLogCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTarget sets the "target" field.
func (_c *EmailLogCreate) SetTarget(v string) *EmailLogCreate {
	_c.mutation.SetTarget(v)
	return _c
}

// SetSubject sets the "subject" field.
func (_c *EmailLogCreate) SetSubject(v string) *EmailLogCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *EmailLogCreate) SetContent(v string) *EmailLogCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetSendStatus sets the "send_status" field.
func (_c *EmailLogCreate) SetSendStatus(v uint8) *EmailLogCreate {
	_c.mutation.SetSendStatus(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *EmailLogCreate) SetProvider(v string) *EmailLogCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetID sets the "id" field.
func (_c *EmailLogCreate) SetID(v uuid.UUID) *EmailLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EmailLogCreate) SetNillableID(v *uuid.UUID) *EmailLogCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the EmailLogMutation object of the builder.
func (_c *EmailLogCreate) Mutation() *EmailLogMutation {
	return _c.mutation
}

// Save creates the EmailLog in the database.
func (_c *EmailLogCreate) Save(ctx context.Context) (*EmailLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EmailLogCreate) SaveX(ctx context.Context) *EmailLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EmailLogCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := emaillog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := emaillog.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := emaillog.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EmailLogCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EmailLog.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EmailLog.updated_at"`)}
	}
	if _, ok := _c.mutation.Target(); !ok {
		return &ValidationError{Name: "target", err: errors.New(`ent: missing required field "EmailLog.target"`)}
	}
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "EmailLog.subject"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "EmailLog.content"`)}
	}
	if _, ok := _c.mutation.SendStatus(); !ok {
		return &ValidationError{Name: "send_status", err: errors.New(`ent: missing required field "EmailLog.send_status"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "EmailLog.provider"`)}
	}
	return nil
}

func (_c *EmailLogCreate) sqlSave(ctx context.Context) (*EmailLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EmailLogCreate) createSpec() (*EmailLog, *sqlgraph.CreateSpec) {
	var (
		_node = &EmailLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(emaillog.Table, sqlgraph.NewFieldSpec(emaillog.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(emaillog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(emaillog.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Target(); ok {
		_spec.SetField(emaillog.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(emaillog.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(emaillog.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.SendStatus(); ok {
		_spec.SetField(emaillog.FieldSendStatus, field.TypeUint8, value)
		_node.SendStatus = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(emaillog.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	return _node, _spec
}

// EmailLogCreateBulk is the builder for creating many EmailLog entities in bulk.
type EmailLogCreateBulk struct {
	config
	err      error
	builders []*EmailLogCreate
}

// Save creates the EmailLog entities in the database.
func (_c *EmailLogCreateBulk) Save(ctx context.Context) ([]*EmailLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EmailLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmailLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EmailLogCreateBulk) SaveX(ctx context.Context) []*EmailLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
