// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	uuid "github.com/gofrs/uuid/v5"
	"github.com/suyuan32/simple-admin-message-center/ent/emaillog"
	"github.com/suyuan32/simple-admin-message-center/ent/emailprovider"
	"github.com/suyuan32/simple-admin-message-center/ent/schema"
	"github.com/suyuan32/simple-admin-message-center/ent/smslog"
	"github.com/suyuan32/simple-admin-message-center/ent/smsprovider"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	emaillogMixin := schema.EmailLog{}.Mixin()
	emaillogMixinFields0 := emaillogMixin[0].Fields()
	_ = emaillogMixinFields0
	emaillogFields := schema.EmailLog{}.Fields()
	_ = emaillogFields
	// emaillogDescCreatedAt is the schema descriptor for created_at field.
	emaillogDescCreatedAt := emaillogMixinFields0[1].Descriptor()
	// emaillog.DefaultCreatedAt holds the default value on creation for the created_at field.
	emaillog.DefaultCreatedAt = emaillogDescCreatedAt.Default.(func() time.Time)
	// emaillogDescUpdatedAt is the schema descriptor for updated_at field.
	emaillogDescUpdatedAt := emaillogMixinFields0[2].Descriptor()
	// emaillog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	emaillog.DefaultUpdatedAt = emaillogDescUpdatedAt.Default.(func() time.Time)
	// emaillog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	emaillog.UpdateDefaultUpdatedAt = emaillogDescUpdatedAt.UpdateDefault.(func() time.Time)
	// emaillogDescID is the schema descriptor for id field.
	emaillogDescID := emaillogMixinFields0[0].Descriptor()
	// emaillog.DefaultID holds the default value on creation for the id field.
	emaillog.DefaultID = emaillogDescID.Default.(func() uuid.UUID)
	emailproviderMixin := schema.EmailProvider{}.Mixin()
	emailproviderMixinFields0 := emailproviderMixin[0].Fields()
	_ = emailproviderMixinFields0
	emailproviderFields := schema.EmailProvider{}.Fields()
	_ = emailproviderFields
	// emailproviderDescCreatedAt is the schema descriptor for created_at field.
	emailproviderDescCreatedAt := emailproviderMixinFields0[1].Descriptor()
	// emailprovider.DefaultCreatedAt holds the default value on creation for the created_at field.
	emailprovider.DefaultCreatedAt = emailproviderDescCreatedAt.Default.(func() time.Time)
	// emailproviderDescUpdatedAt is the schema descriptor for updated_at field.
	emailproviderDescUpdatedAt := emailproviderMixinFields0[2].Descriptor()
	// emailprovider.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	emailprovider.DefaultUpdatedAt = emailproviderDescUpdatedAt.Default.(func() time.Time)
	// emailprovider.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	emailprovider.UpdateDefaultUpdatedAt = emailproviderDescUpdatedAt.UpdateDefault.(func() time.Time)
	// emailproviderDescTLS is the schema descriptor for tls field.
	emailproviderDescTLS := emailproviderFields[8].Descriptor()
	// emailprovider.DefaultTLS holds the default value on creation for the tls field.
	emailprovider.DefaultTLS = emailproviderDescTLS.Default.(bool)
	// emailproviderDescIsDefault is the schema descriptor for is_default field.
	emailproviderDescIsDefault := emailproviderFields[9].Descriptor()
	// emailprovider.DefaultIsDefault holds the default value on creation for the is_default field.
	emailprovider.DefaultIsDefault = emailproviderDescIsDefault.Default.(bool)
	smslogMixin := schema.SmsLog{}.Mixin()
	smslogMixinFields0 := smslogMixin[0].Fields()
	_ = smslogMixinFields0
	smslogFields := schema.SmsLog{}.Fields()
	_ = smslogFields
	// smslogDescCreatedAt is the schema descriptor for created_at field.
	smslogDescCreatedAt := smslogMixinFields0[1].Descriptor()
	// smslog.DefaultCreatedAt holds the default value on creation for the created_at field.
	smslog.DefaultCreatedAt = smslogDescCreatedAt.Default.(func() time.Time)
	// smslogDescUpdatedAt is the schema descriptor for updated_at field.
	smslogDescUpdatedAt := smslogMixinFields0[2].Descriptor()
	// smslog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	smslog.DefaultUpdatedAt = smslogDescUpdatedAt.Default.(func() time.Time)
	// smslog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	smslog.UpdateDefaultUpdatedAt = smslogDescUpdatedAt.UpdateDefault.(func() time.Time)
	// smslogDescID is the schema descriptor for id field.
	smslogDescID := smslogMixinFields0[0].Descriptor()
	// smslog.DefaultID holds the default value on creation for the id field.
	smslog.DefaultID = smslogDescID.Default.(func() uuid.UUID)
	smsproviderMixin := schema.SmsProvider{}.Mixin()
	smsproviderMixinFields0 := smsproviderMixin[0].Fields()
	_ = smsproviderMixinFields0
	smsproviderFields := schema.SmsProvider{}.Fields()
	_ = smsproviderFields
	// smsproviderDescCreatedAt is the schema descriptor for created_at field.
	smsproviderDescCreatedAt := smsproviderMixinFields0[1].Descriptor()
	// smsprovider.DefaultCreatedAt holds the default value on creation for the created_at field.
	smsprovider.DefaultCreatedAt = smsproviderDescCreatedAt.Default.(func() time.Time)
	// smsproviderDescUpdatedAt is the schema descriptor for updated_at field.
	smsproviderDescUpdatedAt := smsproviderMixinFields0[2].Descriptor()
	// smsprovider.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	smsprovider.DefaultUpdatedAt = smsproviderDescUpdatedAt.Default.(func() time.Time)
	// smsprovider.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	smsprovider.UpdateDefaultUpdatedAt = smsproviderDescUpdatedAt.UpdateDefault.(func() time.Time)
	// smsproviderDescIsDefault is the schema descriptor for is_default field.
	smsproviderDescIsDefault := smsproviderFields[4].Descriptor()
	// smsprovider.DefaultIsDefault holds the default value on creation for the is_default field.
	smsprovider.DefaultIsDefault = smsproviderDescIsDefault.Default.(bool)
}
