// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/suyuan32/simple-admin-message-center/ent/predicate"
	"github.com/suyuan32/simple-admin-message-center/ent/smslog"
)

// SmsLogQuery is the builder for querying SmsLog entities.
type SmsLogQuery struct {
	config
	ctx        *QueryContext
	order      []smslog.OrderOption
	inters     []Interceptor
	predicates []predicate.SmsLog
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SmsLogQuery builder.
func (slq *SmsLogQuery) Where(ps ...predicate.SmsLog) *SmsLogQuery {
	slq.predicates = append(slq.predicates, ps...)
	return slq
}

// Limit the number of records to be returned by this query.
func (slq *SmsLogQuery) Limit(limit int) *SmsLogQuery {
	slq.ctx.Limit = &limit
	return slq
}

// Offset to start from.
func (slq *SmsLogQuery) Offset(offset int) *SmsLogQuery {
	slq.ctx.Offset = &offset
	return slq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (slq *SmsLogQuery) Unique(unique bool) *SmsLogQuery {
	slq.ctx.Unique = &unique
	return slq
}

// Order specifies how the records should be ordered.
func (slq *SmsLogQuery) Order(o ...smslog.OrderOption) *SmsLogQuery {
	slq.order = append(slq.order, o...)
	return slq
}

// First returns the first SmsLog entity from the query.
// Returns a *NotFoundError when no SmsLog was found.
func (slq *SmsLogQuery) First(ctx context.Context) (*SmsLog, error) {
	nodes, err := slq.Limit(1).All(setContextOp(ctx, slq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{smslog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (slq *SmsLogQuery) FirstX(ctx context.Context) *SmsLog {
	node, err := slq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SmsLog ID from the query.
// Returns a *NotFoundError when no SmsLog ID was found.
func (slq *SmsLogQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = slq.Limit(1).IDs(setContextOp(ctx, slq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{smslog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (slq *SmsLogQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := slq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SmsLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SmsLog entity is found.
// Returns a *NotFoundError when no SmsLog entities are found.
func (slq *SmsLogQuery) Only(ctx context.Context) (*SmsLog, error) {
	nodes, err := slq.Limit(2).All(setContextOp(ctx, slq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{smslog.Label}
	default:
		return nil, &NotSingularError{smslog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (slq *SmsLogQuery) OnlyX(ctx context.Context) *SmsLog {
	node, err := slq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SmsLog ID in the query.
// Returns a *NotSingularError when more than one SmsLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (slq *SmsLogQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = slq.Limit(2).IDs(setContextOp(ctx, slq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{smslog.Label}
	default:
		err = &NotSingularError{smslog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (slq *SmsLogQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := slq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SmsLogs.
func (slq *SmsLogQuery) All(ctx context.Context) ([]*SmsLog, error) {
	ctx = setContextOp(ctx, slq.ctx, "All")
	if err := slq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SmsLog, *SmsLogQuery]()
	return withInterceptors[[]*SmsLog](ctx, slq, qr, slq.inters)
}

// AllX is like All, but panics if an error occurs.
func (slq *SmsLogQuery) AllX(ctx context.Context) []*SmsLog {
	nodes, err := slq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SmsLog IDs.
func (slq *SmsLogQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if slq.ctx.Unique == nil && slq.path != nil {
		slq.Unique(true)
	}
	ctx = setContextOp(ctx, slq.ctx, "IDs")
	if err = slq.Select(smslog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (slq *SmsLogQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := slq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (slq *SmsLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, slq.ctx, "Count")
	if err := slq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, slq, querierCount[*SmsLogQuery](), slq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (slq *SmsLogQuery) CountX(ctx context.Context) int {
	count, err := slq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (slq *SmsLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, slq.ctx, "Exist")
	switch _, err := slq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (slq *SmsLogQuery) ExistX(ctx context.Context) bool {
	exist, err := slq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SmsLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (slq *SmsLogQuery) Clone() *SmsLogQuery {
	if slq == nil {
		return nil
	}
	return &SmsLogQuery{
		config:     slq.config,
		ctx:        slq.ctx.Clone(),
		order:      append([]smslog.OrderOption{}, slq.order...),
		inters:     append([]Interceptor{}, slq.inters...),
		predicates: append([]predicate.SmsLog{}, slq.predicates...),
		// clone intermediate query.
		sql:  slq.sql.Clone(),
		path: slq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SmsLog.Query().
//		GroupBy(smslog.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (slq *SmsLogQuery) GroupBy(field string, fields ...string) *SmsLogGroupBy {
	slq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SmsLogGroupBy{build: slq}
	grbuild.flds = &slq.ctx.Fields
	grbuild.label = smslog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.SmsLog.Query().
//		Select(smslog.FieldCreatedAt).
//		Scan(ctx, &v)
func (slq *SmsLogQuery) Select(fields ...string) *SmsLogSelect {
	slq.ctx.Fields = append(slq.ctx.Fields, fields...)
	sbuild := &SmsLogSelect{SmsLogQuery: slq}
	sbuild.label = smslog.Label
	sbuild.flds, sbuild.scan = &slq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SmsLogSelect configured with the given aggregations.
func (slq *SmsLogQuery) Aggregate(fns ...AggregateFunc) *SmsLogSelect {
	return slq.Select().Aggregate(fns...)
}

func (slq *SmsLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range slq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, slq); err != nil {
				return err
			}
		}
	}
	for _, f := range slq.ctx.Fields {
		if !smslog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if slq.path != nil {
		prev, err := slq.path(ctx)
		if err != nil {
			return err
		}
		slq.sql = prev
	}
	return nil
}

func (slq *SmsLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SmsLog, error) {
	var (
		nodes = []*SmsLog{}
		_spec = slq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SmsLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SmsLog{config: slq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, slq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (slq *SmsLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := slq.querySpec()
	_spec.Node.Columns = slq.ctx.Fields
	if len(slq.ctx.Fields) > 0 {
		_spec.Unique = slq.ctx.Unique != nil && *slq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, slq.driver, _spec)
}

func (slq *SmsLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(smslog.Table, smslog.Columns, sqlgraph.NewFieldSpec(smslog.FieldID, field.TypeUUID))
	_spec.From = slq.sql
	if unique := slq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if slq.path != nil {
		_spec.Unique = true
	}
	if fields := slq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, smslog.FieldID)
		for i := range fields {
			if fields[i] != smslog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := slq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := slq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := slq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := slq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (slq *SmsLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(slq.driver.Dialect())
	t1 := builder.Table(smslog.Table)
	columns := slq.ctx.Fields
	if len(columns) == 0 {
		columns = smslog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if slq.sql != nil {
		selector = slq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if slq.ctx.Unique != nil && *slq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range slq.predicates {
		p(selector)
	}
	for _, p := range slq.order {
		p(selector)
	}
	if offset := slq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := slq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SmsLogGroupBy is the group-by builder for SmsLog entities.
type SmsLogGroupBy struct {
	selector
	build *SmsLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (slgb *SmsLogGroupBy) Aggregate(fns ...AggregateFunc) *SmsLogGroupBy {
	slgb.fns = append(slgb.fns, fns...)
	return slgb
}

// Scan applies the selector query and scans the result into the given value.
func (slgb *SmsLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, slgb.build.ctx, "GroupBy")
	if err := slgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SmsLogQuery, *SmsLogGroupBy](ctx, slgb.build, slgb, slgb.build.inters, v)
}

func (slgb *SmsLogGroupBy) sqlScan(ctx context.Context, root *SmsLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(slgb.fns))
	for _, fn := range slgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*slgb.flds)+len(slgb.fns))
		for _, f := range *slgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*slgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := slgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SmsLogSelect is the builder for selecting fields of SmsLog entities.
type SmsLogSelect struct {
	*SmsLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sls *SmsLogSelect) Aggregate(fns ...AggregateFunc) *SmsLogSelect {
	sls.fns = append(sls.fns, fns...)
	return sls
}

// Scan applies the selector query and scans the result into the given value.
func (sls *SmsLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sls.ctx, "Select")
	if err := sls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SmsLogQuery, *SmsLogSelect](ctx, sls.SmsLogQuery, sls, sls.inters, v)
}

func (sls *SmsLogSelect) sqlScan(ctx context.Context, root *SmsLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sls.fns))
	for _, fn := range sls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
